#!/usr/bin/env python3
"""
Build "Lecture Notes.app" — a double-clickable wrapper that starts the daemon
and opens the viewer.

    ./build_app.py                 # build into the project directory
    ./build_app.py --desktop       # ...and drop an alias on the Desktop

Re-run it if you move the project or change Python environments; the paths are
baked into the launcher at build time.
"""

from __future__ import annotations

import argparse
import os
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
APP_NAME = "Lecture Notes"
BUNDLE_ID = "local.lecturescrape.viewer"
PORT = 8420

LAUNCHER = r"""#!/bin/bash
# Generated by build_app.py — do not edit; re-run the builder instead.

ROOT={root}
PY={python}
PORT={port}
LOG="$HOME/Library/Logs/lecturescrape.log"

# A GUI app inherits none of your shell environment, so yt-dlp, ffmpeg and
# friends have to be put back on PATH explicitly.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

mkdir -p "$(dirname "$LOG")"

fail() {{
    /usr/bin/osascript -e "display alert \"Lecture Notes\" message \"$1\" as critical"
    exit 1
}}

[ -x "$PY" ] || fail "Python not found at $PY. Re-run build_app.py."
[ -f "$ROOT/lecturescrape.py" ] || fail "lecturescrape.py not found in $ROOT. Re-run build_app.py."

up() {{ /usr/bin/curl -fs -m 2 "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; }}

STARTED_BY_US=0
if ! up; then
    echo "--- $(date) launching daemon ---" >>"$LOG"
    "$PY" "$ROOT/lecturescrape.py" serve >>"$LOG" 2>&1 &
    DAEMON=$!
    STARTED_BY_US=1

    for _ in $(seq 1 60); do
        up && break
        # If it died on startup, surface the reason rather than spinning.
        if ! kill -0 "$DAEMON" 2>/dev/null; then
            fail "The daemon quit on startup. Last log lines:
$(tail -n 6 "$LOG")"
        fi
        sleep 0.25
    done

    up || fail "The daemon didn't come up on port $PORT. See $LOG"
fi

# An app-mode window has no address bar, so it feels like a real app rather
# than a browser tab. Fall back to the default browser if Chrome isn't there.
URL="http://127.0.0.1:$PORT"
if [ -d "/Applications/Google Chrome.app" ]; then
    open -na "Google Chrome" --args --app="$URL" >/dev/null 2>&1 || open "$URL"
else
    open "$URL"
fi

# Only hold the process — and so the Dock icon — if we own the daemon. If it
# was already running from a terminal, quitting the app must not kill it.
if [ "$STARTED_BY_US" = "1" ]; then
    trap 'kill $DAEMON 2>/dev/null' EXIT INT TERM
    wait $DAEMON
fi
"""


def draw_icon(px: int = 1024):
    """A note card with a play badge — 'a lecture, written down'.

    Drawn rather than shipped so there's no binary blob in the repo. Everything
    is deliberately heavy: at 16px in the Dock, thin strokes disappear, so the
    card is large, the text bars are few and thick, and the badge breaks the
    card's edge to keep a recognisable silhouette.
    """
    from PIL import Image, ImageDraw, ImageFilter

    S = px * 2  # supersample, downscaled at the end for clean edges
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))

    # Violet gradient tile — distinctive next to the sea of blue app icons.
    grad = Image.new("RGB", (1, S))
    top, bot = (99, 91, 255), (48, 33, 128)
    for y in range(S):
        t = y / (S - 1)
        grad.putpixel((0, y), tuple(round(top[i] + (bot[i] - top[i]) * t)
                                    for i in range(3)))
    grad = grad.resize((S, S))

    mask = Image.new("L", (S, S), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, S - 1, S - 1],
                                           radius=int(S * 0.225), fill=255)
    img.paste(grad, (0, 0), mask)

    # Card, drawn on its own layer so it can be rotated with a soft shadow.
    card = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    cd = ImageDraw.Draw(card)
    L, T, R, B = int(S * .19), int(S * .165), int(S * .70), int(S * .70)
    cd.rounded_rectangle([L, T, R, B], radius=int(S * .05),
                         fill=(255, 255, 255, 255))

    # Two bars, not three. A third one turns into an illegible smudge at 16px.
    bar_x, bar_w = L + int(S * .075), int(S * .36)
    for i, col in enumerate([(99, 91, 255, 255), (156, 163, 183, 255)]):
        y = T + int(S * .125) + i * int(S * .165)
        cd.rounded_rectangle([bar_x, y, bar_x + (bar_w if i == 0 else int(bar_w * .72)),
                              y + int(S * .085)],
                             radius=int(S * .042), fill=col)

    shadow = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle([L, T, R, B], radius=int(S * .05),
                                             fill=(18, 10, 55, 130))
    shadow = shadow.rotate(-4, resample=Image.BICUBIC).filter(
        ImageFilter.GaussianBlur(S * .016))
    img.alpha_composite(Image.alpha_composite(
        shadow, card.rotate(-4, resample=Image.BICUBIC)))

    # Play badge, big and overlapping the card corner. It carries the icon at
    # small sizes, so it needs mass rather than detail.
    cx, cy, r = int(S * .705), int(S * .70), int(S * .225)
    badge = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    bd = ImageDraw.Draw(badge)
    ring = int(S * .028)
    bd.ellipse([cx - r - ring, cy - r - ring, cx + r + ring, cy + r + ring],
               fill=(255, 255, 255, 255))            # keyline against the card
    bd.ellipse([cx - r, cy - r, cx + r, cy + r], fill=(255, 176, 32, 255))
    t = int(r * .48)
    bd.polygon([(cx - t + int(r * .10), cy - int(t * 1.2)),
                (cx - t + int(r * .10), cy + int(t * 1.2)),
                (cx + int(t * 1.3), cy)], fill=(40, 24, 6, 255))
    img.alpha_composite(badge)

    return img.resize((px, px), Image.LANCZOS)


def build_icon(resources: Path) -> str | None:
    try:
        from PIL import Image
    except ImportError:
        print("  (Pillow missing — skipping icon)")
        return None

    img = draw_icon(1024)
    iconset = resources.parent / "icon.iconset"
    if iconset.exists():
        shutil.rmtree(iconset)
    iconset.mkdir(parents=True)

    for px in (16, 32, 64, 128, 256, 512, 1024):
        img.resize((px, px), Image.LANCZOS).save(iconset / f"icon_{px}x{px}.png")
        if px > 16:
            img.resize((px, px), Image.LANCZOS).save(
                iconset / f"icon_{px // 2}x{px // 2}@2x.png")

    icns = resources / "icon.icns"
    proc = subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(icns)],
                          capture_output=True, text=True)
    shutil.rmtree(iconset, ignore_errors=True)
    if proc.returncode != 0:
        print(f"  (iconutil failed: {proc.stderr.strip()[:120]})")
        return None
    return "icon.icns"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--desktop", action="store_true",
                    help="also put an alias on the Desktop")
    ap.add_argument("--python", default=sys.executable,
                    help="interpreter the daemon runs under")
    args = ap.parse_args()

    python = Path(args.python).resolve()
    if not (python.exists() and os.access(python, os.X_OK)):
        sys.exit(f"error: {python} isn't an executable interpreter")

    app = ROOT / f"{APP_NAME}.app"
    if app.exists():
        shutil.rmtree(app)
    macos = app / "Contents" / "MacOS"
    resources = app / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    print(f"building {app.name}")
    print(f"  project : {ROOT}")
    print(f"  python  : {python}")

    icon = build_icon(resources)

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": "1.0",
        "CFBundleShortVersionString": "1.0",
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": "launcher",
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "11.0",
    }
    if icon:
        info["CFBundleIconFile"] = icon
    (app / "Contents" / "Info.plist").write_bytes(plistlib.dumps(info))

    launcher = macos / "launcher"
    # shlex-style quoting so a path containing spaces survives.
    launcher.write_text(LAUNCHER.format(
        root=f'"{ROOT}"', python=f'"{python}"', port=PORT))
    launcher.chmod(0o755)

    # Clear the quarantine flag so Gatekeeper doesn't refuse a locally built app.
    subprocess.run(["xattr", "-cr", str(app)], capture_output=True)

    print(f"  built   : {app}")

    if args.desktop:
        link = Path.home() / "Desktop" / f"{APP_NAME}.app"
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(app)
        print(f"  desktop : {link}")

    print("\nDouble-click it. First launch may take a few seconds while the "
          "daemon starts.")


if __name__ == "__main__":
    main()
